site_name: FuzzyFileNav Documentation
site_url: https://facelessuser.github.io/FuzzyFileNav
repo_url: https://github.com/facelessuser/FuzzyFileNav
edit_uri: tree/master/docs/src/markdown
site_description: A Sublime Text plugin navigating the file system.
copyright: |
  Copyright &copy; 2011 - 2021 <a href="https://github.com/facelessuser"  target="_blank" rel="noopener">Isaac Muse</a>

docs_dir: docs/src/markdown
theme:
  custom_dir: docs/theme
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
  pymdownx:
    sponsor: "https://github.com/sponsors/facelessuser"

nav:
  - About FuzzyFileNav: index.md
  - Installation: installation.md
  - User Guide: usage.md
  - About:
    - Contributing &amp; Support: about/contributing.md
    - License: about/license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: FuzzyFileNav
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
      - docs/src/markdown/_snippets
      auto_append:
      - refs.md
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
       alternate_style: true
  - pymdownx.saneheaders:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser
    - icon: fontawesome/brands/discord
      link: https://discord.gg/TWs8Tgr

plugins:
  - search
  - git-revision-date-localized
  - mkdocs_pymdownx_material_extras
  - minify:
      minify_html: true
